insert into blog values(1,'science','science.com','1998-04-07');
insert into blog values(2,'maths','maths.com','1998-04-08');
select * from blog;
insert into category values(1,'physics',1,null);
insert into category values(2,'chemistry',1,null);
insert into category values(3,'optics',1,1);
insert into category values(4,'organic',1,2);
select * from category;
insert into post values(1,'refraction','manoj',3,'1998-05-07');
insert into post values(2,'benzene','harsha',4,'1998-05-16');
select * from post;
select * from comments;
insert into author values(1,'manoj','optics expert');
insert into author values(2,'harsha','organic expert');
select * from author;
insert into tag values(1,'good');
insert into tag values(2,'bad');
select * from tag;
insert into post_tag values(1,1);
insert into post_tag values(2,2);
select * from post_tag;
insert into post_author values(1,1);
insert into post_author values(2,2);
select * from post_author;
create table employee(emp_name varchar(20) not null, salary int unsigned  not null); 
